version: "3.9"
services:
  university_db:
    container_name: universityDB
    image: postgres
    environment:
      POSTGRES_USER: university
      POSTGRES_PASSWORD: Postgres243
      POSTGRES_DB: universityDB
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    restart: always
    ports:
      - 5432:5432

